application: bumpybot
version: 0-0-1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: bumpy_bot.py
- url: /assets
  static_dir: assets
- url: /pull.*
  script: bumpy/pull.py
- url: /push.*
  script: bumpy/push.py